package lt.vu.mybatis.model;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.FIRSTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.PERSONALCODE
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private String personalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.FIRSTNAME
     *
     * @return the value of PUBLIC.AUTHOR.FIRSTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.AUTHOR.FIRSTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @return the value of PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.LASTNAME
     *
     * @param lastname the value for PUBLIC.AUTHOR.LASTNAME
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.PERSONALCODE
     *
     * @return the value of PUBLIC.AUTHOR.PERSONALCODE
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public String getPersonalcode() {
        return personalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.PERSONALCODE
     *
     * @param personalcode the value for PUBLIC.AUTHOR.PERSONALCODE
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setPersonalcode(String personalcode) {
        this.personalcode = personalcode;
    }
}