package lt.vu.mybatis.model;

public class BookGenres {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK_GENRES.BOOKS_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private Integer booksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK_GENRES.GENRES_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    private Integer genresId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK_GENRES.BOOKS_ID
     *
     * @return the value of PUBLIC.BOOK_GENRES.BOOKS_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public Integer getBooksId() {
        return booksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK_GENRES.BOOKS_ID
     *
     * @param booksId the value for PUBLIC.BOOK_GENRES.BOOKS_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setBooksId(Integer booksId) {
        this.booksId = booksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK_GENRES.GENRES_ID
     *
     * @return the value of PUBLIC.BOOK_GENRES.GENRES_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public Integer getGenresId() {
        return genresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK_GENRES.GENRES_ID
     *
     * @param genresId the value for PUBLIC.BOOK_GENRES.GENRES_ID
     *
     * @mbg.generated Mon May 11 21:42:15 EEST 2020
     */
    public void setGenresId(Integer genresId) {
        this.genresId = genresId;
    }
}